import { ChannelCategory } from "../types";

export const googleCategories: ChannelCategory[] = [
  { id: "1", path: "Animals & Pet Supplies" },
  { id: "4", path: "Animals & Pet Supplies > Pet Supplies > Cat Supplies" },
  { id: "5", path: "Animals & Pet Supplies > Pet Supplies > Dog Supplies" },
  { id: "3530", path: "Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Food" },
  { id: "5010", path: "Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Toys" },
  { id: "166", path: "Apparel & Accessories" },
  { id: "1604", path: "Apparel & Accessories > Clothing" },
  { id: "212", path: "Apparel & Accessories > Clothing > Shirts & Tops" },
  { id: "204", path: "Apparel & Accessories > Clothing > Pants" },
  { id: "187", path: "Apparel & Accessories > Shoes" },
  { id: "178", path: "Apparel & Accessories > Clothing Accessories > Sunglasses" },
  { id: "188", path: "Apparel & Accessories > Jewelry" },
  { id: "201", path: "Apparel & Accessories > Jewelry > Watches" },
  { id: "8", path: "Arts & Entertainment" },
  { id: "216", path: "Arts & Entertainment > Hobbies & Creative Arts > Collectibles" },
  { id: "54", path: "Arts & Entertainment > Hobbies & Creative Arts > Musical Instruments" },
  { id: "96", path: "Arts & Entertainment > Party & Celebration > Party Supplies" },
  { id: "53", path: "Arts & Entertainment > Party & Celebration > Gift Giving > Gift Cards & Certificates" },
  { id: "537", path: "Baby & Toddler" },
  { id: "568", path: "Baby & Toddler > Baby Transport > Baby Strollers" },
  { id: "551", path: "Baby & Toddler > Diapering > Diapers" },
  { id: "564", path: "Baby & Toddler > Nursing & Feeding > Baby Bottles" },
  { id: "111", path: "Business & Industrial" },
  { id: "1624", path: "Business & Industrial > Science & Laboratory" },
  { id: "976", path: "Business & Industrial > Signage" },
  { id: "141", path: "Cameras & Optics" },
  { id: "147", path: "Cameras & Optics > Camera & Optic Accessories > Camera Lens Accessories > Lens Filters" },
  { id: "222", path: "Electronics" },
  { id: "536", path: "Home & Garden" },
  { id: "469", path: "Health & Beauty" },
  { id: "988", path: "Sporting Goods" },
  { id: "1239", path: "Toys & Games" },
];